/**
 * Proposito: Datos territoriales estaticos y versionados para los formularios
 *            de direccion (iteracion 1-geo).
 * Contenido: PROVINCIAS (24, nombres oficiales de Georef/INDEC) y
 *            PARTIDOS_BUENOS_AIRES (135 partidos = departamentos de la
 *            provincia de Buenos Aires en Georef).
 * Fuente: https://apis.datos.gob.ar/georef/api/provincias y
 *         https://apis.datos.gob.ar/georef/api/departamentos?provincia=06
 *         (exportados tal cual; los nombres coinciden con los que el backend
 *         envia como filtro a Georef y persiste normalizados).
 * Nota: los datos territoriales oficiales no cambian regularmente; si Georef
 *       actualizara un nombre, se versiona en este archivo sin tocar logica.
 */

export const PROVINCIAS = [
  'Buenos Aires',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Ciudad Autónoma de Buenos Aires',
  'Córdoba',
  'Corrientes',
  'Entre Ríos',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Tierra del Fuego, Antártida e Islas del Atlántico Sur',
  'Tucumán',
];

// Partidos de la provincia de Buenos Aires (unidad 'departamento' de Georef).
// Obligatorio en el formulario cuando la provincia es 'Buenos Aires'.
export const PARTIDOS_BUENOS_AIRES = [
  '25 de Mayo',
  '9 de Julio',
  'Adolfo Alsina',
  'Adolfo Gonzales Chaves',
  'Alberti',
  'Almirante Brown',
  'Arrecifes',
  'Avellaneda',
  'Ayacucho',
  'Azul',
  'Bahía Blanca',
  'Balcarce',
  'Baradero',
  'Benito Juárez',
  'Berazategui',
  'Berisso',
  'Bolívar',
  'Bragado',
  'Brandsen',
  'Campana',
  'Cañuelas',
  'Capitán Sarmiento',
  'Carlos Casares',
  'Carlos Tejedor',
  'Carmen de Areco',
  'Castelli',
  'Chacabuco',
  'Chascomús',
  'Chivilcoy',
  'Colón',
  'Coronel de Marina Leonardo Rosales',
  'Coronel Dorrego',
  'Coronel Pringles',
  'Coronel Suárez',
  'Daireaux',
  'Dolores',
  'Ensenada',
  'Escobar',
  'Esteban Echeverría',
  'Exaltación de la Cruz',
  'Ezeiza',
  'Florencio Varela',
  'Florentino Ameghino',
  'General Alvarado',
  'General Alvear',
  'General Arenales',
  'General Belgrano',
  'General Guido',
  'General Juan Madariaga',
  'General La Madrid',
  'General Las Heras',
  'General Lavalle',
  'General Paz',
  'General Pinto',
  'General Pueyrredón',
  'General Rodríguez',
  'General San Martín',
  'General Viamonte',
  'General Villegas',
  'Guaminí',
  'Hipólito Yrigoyen',
  'Hurlingham',
  'Ituzaingó',
  'José C. Paz',
  'Junín',
  'La Costa',
  'La Matanza',
  'La Plata',
  'Lanús',
  'Laprida',
  'Las Flores',
  'Leandro N. Alem',
  'Lezama',
  'Lincoln',
  'Lobería',
  'Lobos',
  'Lomas de Zamora',
  'Luján',
  'Magdalena',
  'Maipú',
  'Malvinas Argentinas',
  'Mar Chiquita',
  'Marcos Paz',
  'Mercedes',
  'Merlo',
  'Monte',
  'Monte Hermoso',
  'Moreno',
  'Morón',
  'Navarro',
  'Necochea',
  'Olavarría',
  'Patagones',
  'Pehuajó',
  'Pellegrini',
  'Pergamino',
  'Pila',
  'Pilar',
  'Pinamar',
  'Presidente Perón',
  'Puán',
  'Punta Indio',
  'Quilmes',
  'Ramallo',
  'Rauch',
  'Rivadavia',
  'Rojas',
  'Roque Pérez',
  'Saavedra',
  'Saladillo',
  'Salliqueló',
  'Salto',
  'San Andrés de Giles',
  'San Antonio de Areco',
  'San Cayetano',
  'San Fernando',
  'San Isidro',
  'San Miguel',
  'San Nicolás',
  'San Pedro',
  'San Vicente',
  'Suipacha',
  'Tandil',
  'Tapalqué',
  'Tigre',
  'Tordillo',
  'Tornquist',
  'Trenque Lauquen',
  'Tres Arroyos',
  'Tres de Febrero',
  'Tres Lomas',
  'Vicente López',
  'Villa Gesell',
  'Villarino',
  'Zárate',
];
